// Package keystore abstracts where Rempart's private keys live.
//
// Two backends exist:
//   - "software": keys are generated by Rempart and stored encrypted on disk
//     under a master key derived from a passphrase (Argon2id).
//   - "pkcs11": keys are generated inside a Hardware Security Module and never
//     leave it. Signing (DNSSEC, TLS, audit) and wrapping of data-encryption
//     keys (query log, sealed state) happen inside the HSM.
//
// Everything else in Rempart only sees crypto.Signer and Wrap/Unwrap, so
// switching from software to HSM is a configuration change.
package keystore

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"errors"
	"fmt"
	"strings"
)

// Algorithm is a signing key algorithm.
type Algorithm string

const (
	ECDSAP256 Algorithm = "ECDSAP256"
	ECDSAP384 Algorithm = "ECDSAP384"
	Ed25519   Algorithm = "ED25519"
)

// ParseAlgorithm accepts DNSSEC-style names ("ECDSAP256SHA256") too.
func ParseAlgorithm(s string) (Algorithm, error) {
	switch strings.ToUpper(strings.TrimSpace(s)) {
	case "", "ECDSAP256", "ECDSAP256SHA256", "P256", "13":
		return ECDSAP256, nil
	case "ECDSAP384", "ECDSAP384SHA384", "P384", "14":
		return ECDSAP384, nil
	case "ED25519", "15":
		return Ed25519, nil
	}
	return "", fmt.Errorf("algorithme de clé inconnu: %q", s)
}

// ErrNotFound is returned when a key does not exist and create=false.
var ErrNotFound = errors.New("clé introuvable")

// KeyInfo describes a key for display (never contains private material).
type KeyInfo struct {
	Label     string    `json:"label"`
	Algorithm Algorithm `json:"algorithm"`
	Backend   string    `json:"backend"`
	// Fingerprint is the SHA-256 of the public key (hex, shortened).
	Fingerprint string `json:"fingerprint"`
	// Origin : "générée" (dans le HSM, CKA_LOCAL vrai), "importée" (entrée
	// dans le HSM lors d'une migration) ou "logiciel".
	Origin string `json:"origin"`
}

// Keystore is implemented by the software and PKCS#11 backends.
type Keystore interface {
	// Backend returns "software" or "pkcs11".
	Backend() string
	// Describe returns a human readable description (token label, path…).
	Describe() string
	// Signer returns the signing key with this label. When create is true
	// and the key does not exist, it is generated with the given algorithm.
	Signer(label string, alg Algorithm, create bool) (crypto.Signer, error)
	// Wrap encrypts a small secret (typically a 32-byte data key) with the
	// master key-encryption key. The KEK never leaves the keystore.
	Wrap(plaintext, aad []byte) ([]byte, error)
	// Unwrap reverses Wrap. It fails if the ciphertext or aad was modified.
	Unwrap(ciphertext, aad []byte) ([]byte, error)
	// Keys lists the signing keys known to the keystore.
	Keys() []KeyInfo
	// Destroy supprime définitivement une clé de signature (fin de vie d'une
	// clé DNSSEC après rotation). Une clé absente n'est pas une erreur.
	Destroy(label string) error
	Close() error
}

// AlgorithmOf infers the Algorithm of a public key.
func AlgorithmOf(pub crypto.PublicKey) (Algorithm, error) {
	switch k := pub.(type) {
	case *ecdsa.PublicKey:
		switch k.Curve {
		case elliptic.P256():
			return ECDSAP256, nil
		case elliptic.P384():
			return ECDSAP384, nil
		}
	case ed25519.PublicKey:
		return Ed25519, nil
	}
	return "", fmt.Errorf("type de clé publique non supporté: %T", pub)
}

// AlgorithmInfo décrit un algorithme de signature DNSSEC proposé à la
// création d'une zone, et s'il peut être généré dans le keystore en service.
type AlgorithmInfo struct {
	ID        string `json:"id"`     // nom DNSSEC (RFC 8624) : ECDSAP256SHA256…
	Number    uint8  `json:"number"` // numéro IANA
	Name      string `json:"name"`
	Supported bool   `json:"supported"`
	Reason    string `json:"reason,omitempty"`
}

// algoChecker est implémenté par les keystores qui ne savent pas générer
// tous les algorithmes (un HSM n'offre pas forcément Ed25519).
type algoChecker interface {
	supports(Algorithm) error
}

// Supports indique si le keystore peut générer une clé de cet algorithme.
func Supports(ks Keystore, alg Algorithm) error {
	if c, ok := ks.(algoChecker); ok {
		return c.supports(alg)
	}
	return nil
}

// SigningAlgorithms liste les algorithmes DNSSEC proposés, dans l'ordre
// recommandé, avec leur disponibilité dans ce keystore.
func SigningAlgorithms(ks Keystore) []AlgorithmInfo {
	list := []struct {
		alg  Algorithm
		id   string
		num  uint8
		name string
	}{
		{ECDSAP256, "ECDSAP256SHA256", 13, "ECDSA P-256 (recommandé)"},
		{ECDSAP384, "ECDSAP384SHA384", 14, "ECDSA P-384"},
		{Ed25519, "ED25519", 15, "Ed25519"},
	}
	out := make([]AlgorithmInfo, 0, len(list))
	for _, a := range list {
		i := AlgorithmInfo{ID: a.id, Number: a.num, Name: a.name, Supported: true}
		if err := Supports(ks, a.alg); err != nil {
			i.Supported, i.Reason = false, err.Error()
		}
		out = append(out, i)
	}
	return out
}
